-- MySQL Script generated by MySQL Workbench
-- Fri Jun 12 14:23:26 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema appointments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appointments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appointments` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `appointments` ;

-- -----------------------------------------------------
-- Table `appointments`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appointments`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `dob` DATETIME NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appointments`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appointments`.`appointments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_datetime` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT NULL,
  `tasks` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_appointments_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_appointments_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `appointments`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
